[package]
name = "tase"
version = "0.1.0"
authors = ["Darren Thompson <me@dtho.mp>"]

[dependencies]
rand = "0.5.4"
reqwest = "0.8.6"
rocket = "0.4.4"
rocket_contrib = "0.4.4"
serde = "1.0.24"
serde_json = "1.0.24"
serde_derive = "1.0.24"
chrono = "0.4"
chrono-tz = "0.5"
